-- 0058: make ZIP privacy structural, not a client convention.
--
-- profiles.zip_code was always meant to be private, but the column-level
-- SELECT grant let any authenticated account read every user's ZIP through
-- the raw API. The revoke was deliberately deferred until the deployed web
-- app stopped selecting the column directly; that shipped today (LoginClient
-- now reads its own row through my_profile()), so it is finally safe.
--
-- Owner reads keep working through my_profile() (SECURITY DEFINER, pinned to
-- auth.uid()) on both web and mobile. UPDATE is untouched, so saving a ZIP
-- from the profile editor still works.
revoke select (zip_code) on public.profiles from anon, authenticated;